### ISSUE TITLE
No source for ruby-2.0.0-p643

### ISSUE THREAD

**Issue by net1957** [os97673/debase-ruby_core_source#3]
On windows after update to the latest ruby 2.0.0 patch level i get this message when installing updating ruby-debug-ide (used with rubymine):

````
No source for ruby-2.0.0-p643 provided with debase-ruby_core_source gem
````

Could  you add support for it ?
Regards

**Comment by os97673** [comment]
Fixed

**Comment by net1957** [comment]
Nice. Thanks.

**Comment by PositiveAlex** [comment]
It's still not work using `gem install` on `windows 7 x64` with `x32 ruby 2.0 p643` through `rubygems.org`.

Versions `0.1.2` and `0.1.3.beta1` showed up the error message:

<pre>
C:\Users\alexander.iljushkin>gem install debase -v 0.1.3.beta1
Temporarily enhancing PATH to include DevKit...
Building native extensions.  This could take a while...
ERROR:  Error installing debase:
        ERROR: Failed to build gem native extension.

    C:/Ruby200/bin/ruby.exe -r ./siteconf20150324-2920-t2uemp.rb extconf.rb
checking for vm_core.h... no
checking for vm_core.h... no
Makefile creation failed
**************************************************************************
No source for ruby-2.0.0-p643 provided with debase-ruby_core_source gem.
**************************************************************************
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=C:/Ruby200/bin/ruby
        --with-ruby-dir
        --without-ruby-dir
        --with-ruby-include
        --without-ruby-include=${ruby-dir}/include
        --with-ruby-lib
        --without-ruby-lib=${ruby-dir}/

extconf failed, exit code 1

Gem files will remain installed in C:/Ruby200/lib/ruby/gems/2.0.0/gems/debase-0.1.3.beta1 for inspection.
Results logged to C:/Ruby200/lib/ruby/gems/2.0.0/extensions/x86-mingw32/2.0.0/debase-0.1.3.beta1/gem_make.out
</pre>

**Comment by os97673** [comment]
@PositiveAlex what version of debase-ruby_core_source do you have installed in the sdk?

**Comment by PositiveAlex** [comment]
Im not sure i have one. I installed ruby 2.0, installed devkit. Opened
rubymine and tried to debug. Then it said that it couldnt install because
theres no sources or something what the report says.

23:28, Вт, 24.03.2015, Oleg Sukhodolsky <notifications@github.com>:

**Comment by os97673** [comment]
try `gem list debase-ruby_core_source`

**Comment by PositiveAlex** [comment]
Thank you, Oleg

<pre>
*** LOCAL GEMS ***

debase-ruby_core_source (0.7.7)
</pre>

пт, 27 марта 2015 г. в 0:16, Oleg Sukhodolsky <notifications@github.com>:

**Comment by PositiveAlex** [comment]
Thank you, Oleg

<pre>
*** LOCAL GEMS ***

debase-ruby_core_source (0.7.7)
</pre>

**Comment by os97673** [comment]
you need to install 0.7.8 `gem install debase-ruby_core_source -v '0.7.8'`

**Comment by PositiveAlex** [comment]
Thank you, Oleg, it worked. Have a nice day.

16:21, Пт, 27.03.2015, Oleg Sukhodolsky <notifications@github.com>:

**Comment by ricardograca** [comment]
I have `debase-ruby_core_source` 0.7.8 installed. Trying to install debugger 1.6.6 and I'm getting this error. Any ideas?

**Comment by os97673** [comment]
Well, most likely because debugger uses debugger-ruby_core_source for this, not debase-ruby_core_source.  Also debugger doesn't support 2.0 well :(

**Comment by ricardograca** [comment]
Oops. Yo're right. Sorry about the mixup. Very similar gem name and this was the top result when searching for the error relating to debugger.
